# Configuration file for custom scenarios for `premise`

---

production pathways:
  NCA:
    production volume:
      variable: Share|NCA
    ecoinvent alias:
      name: battery cell production, Li-ion, NCA
      reference product: battery cell, Li-ion, NCA
      exists in original database: True
      efficiency:
      - variable: Efficiency|Electricity|NCA
        includes:
          technosphere:
            - market group for electricity, medium voltage
      efficiency:
      - variable: Efficiency|Heat|NCA
        includes:
          technosphere:
            - market for heat



  NMC532andNMC622:
    production volume:
      variable: Share|NMC532andNMC622
    ecoinvent alias:
      name: battery cell, NMC-622
      reference product: battery cell
      exists in original database: True

      efficiency:
      - variable: Efficiency|Electricity|NMC532andNMC622
        includes:
          technosphere:
            - market group for electricity, medium voltage
      efficiency:
      - variable: Efficiency|Heat|NMC532andNMC622
        includes:
          technosphere:
            - market for heat

  NMC811andNMC900:
    production volume:
      variable: Share|NMC811andNMC900
    ecoinvent alias:
      name: battery cell production, Li-ion, NMC811
      reference product: battery cell, Li-ion, NMC811
      exists in original database: True
      efficiency:
      - variable: Efficiency|Electricity|NMC811andNMC900
        includes:
          technosphere:
            - market group for electricity, medium voltage
      efficiency:
      - variable: Efficiency|Heat|NMC811andNMC900
        includes:
          technosphere:
            - market for heat

  LFP:
    production volume:
      variable: Share|LFP
    ecoinvent alias:
      name: battery cell production, Li-ion, LFP
      reference product: battery cell, Li-ion, LFP
      exists in original database: True
      efficiency:
      - variable: Efficiency|Electricity|LFP
        includes:
          technosphere:
            - market group for electricity, medium voltage
      efficiency:
      - variable: Efficiency|Heat|LFP
        includes:
          technosphere:
            - market for heat

  PLIB:
    production volume:
      variable: Share|PLIB
    ecoinvent alias:
      name: battery cell production, Li-ion, NCA
      reference product: battery cell, Li-ion, NCA
      exists in original database: False
      new dataset: True
      efficiency:
      - variable: Efficiency|Electricity|PLIB
        includes:
          technosphere:
            - market group for electricity, medium voltage
      efficiency:
      - variable: Efficiency|Heat|PLIB
        includes:
          technosphere:
            - market for heat

            
   Marketforheatnaturalgas:
    production volume:
      variable: Share|Heat|Natural Gas|NCA
    ecoinvent alias:
      name: market group for heat, district or industrial, natural gas
      reference product: heat, district or industrial, natural gas
    
    Marketforheatpumps:
    production volume:
      variable: Share|Heat|Heat pumps|NCA
    ecoinvent alias:
      name: market for heat pump, heat and power co-generation unit, 160kW electrical
      reference product: heat pump, heat and power co-generation unit, 160kW electrical




markets:
  - name: market for battery cell production
    reference product: battery cell types
    unit: kilogram
    includes:
      - NCA
      - NMC532andNMC622
      - NMC811andNMC900
      - LFP
      - PLIB


  - name: market for heat
    reference product: heat
    unit: megajoule
    includes:
      - Marketforheatnaturalgas
      - Marketforheatpumps
    replaces:
      name: market group for heat, district or industrial, natural gas
      reference product: heat, district or industrial, natural gas
      operator: equals

    replaces in:
      name: battery cell
      reference product: battery cell
      operator: contains


#  - replace:
#  - name: market group for heat, district or industrial, natural gas
#    reference product: heat, district or industrial, natural gas
#    operator: equals




